///////////////////////////////////////////////////////////////////////////
// Description: Data Access class for the table 'PhieuXuat_ChiTiet_TheKho'
// Generated by LLBLGen v1.3.5996.26197 Final on: Tuesday, August 28, 2018, 8:58:16 AM
// Because the Base Class already implements IDispose, this class doesn't.
///////////////////////////////////////////////////////////////////////////
using System;
using System.Data;
using System.Data.SqlTypes;
using System.Data.SqlClient;

namespace QLKho
{
	/// <summary>
	/// Purpose: Data Access class for the table 'PhieuXuat_ChiTiet_TheKho'.
	/// </summary>
	public partial class clsPhieuXuat_ChiTiet_TheKho : clsDBInteractionBase
	{
        

	}
}
